In [73]:
import seaborn as sns
df = sns.load_dataset('tips')
df

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [75]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [76]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [77]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [78]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [79]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [80]:
## independent and dependent features
X = df[['tip', 'sex', 'smoker', 'day', 'time', 'size']] # ind. feature always a 2d matrix
y = df['total_bill'] # 1d matrix always

In [81]:
## train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [82]:
X_test

,tip,sex,smoker,day,time,size
24,3.18,Male,No,Sat,Dinner,2
6,2.00,Male,No,Sun,Dinner,2
153,2.00,Male,No,Sun,Dinner,4
211,5.16,Male,Yes,Sat,Dinner,4
198,2.00,Female,Yes,Thur,Lunch,2
...,...,...,...,...,...,...
172,5.15,Male,Yes,Sun,Dinner,2
242,1.75,Male,No,Sat,Dinner,2
152,2.74,Male,No,Sun,Dinner,3
231,3.00,Male,Yes,Sat,Dinner,3


In [83]:
## Feature Encoding (Label Encoding and One-hot Encoding)

## Label encoding : when there are 2 categories
## One-hot encoding : when there are more than 2 categories
 
## for 2 categories
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

X_train['sex'] = le1.fit_transform(X_train['sex'])  

X_train['smoker'] = le2.fit_transform(X_train['smoker'])  

X_train['time'] = le3.fit_transform(X_train['time'])  

X_test['sex'] = le1.transform(X_test['sex'])  # not using fit_transform to avoid data leakage

X_test['smoker'] = le2.transform(X_test['smoker'])  

X_test['time'] = le3.transform(X_test['time']) 


## for > 2 categories
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
  transformers=[
      (
        'onehot',
        OneHotEncoder(drop='first'),
        [3],   # as 'day' is third index in the dataset. Check in X_train; 'day' at index=3
      )
    ],
    remainder = 'passthrough'
)


import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

X_train = ct.fit_transform(X_train)

In [84]:
X_train

array([[ 0.  ,  1.  ,  0.  ,  3.5 ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  5.65,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  2.5 ,  0.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.01,  1.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  4.08,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  2.09,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  ,  3.41,  1.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  3.48,  1.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  2.  ,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  1.  ,  0.  ,  5.  ],
       [ 0.  ,  0.  ,  1.  ,  2.71,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  0.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.

In [85]:
X_test = ct.transform(X_test)  # not using fit_transform to avoid data leakage
X_test


array([[1.  , 0.  , 0.  , 3.18, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 5.16, 1.  , 1.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.56, 1.  , 1.  , 1.  , 2.  ],
       [0.  , 0.  , 1.  , 2.52, 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.23, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 3.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.  , 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.47, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.5 , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.83, 0.  , 0.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.36, 0.  , 0.  , 1.  , 3.  ],
       [0.  , 0.  , 1.  , 4.  , 1.  , 1.  , 1.  , 3.  ],
       [0.  , 1.  , 0.  , 3.92,

# SVR

In [86]:
from sklearn.svm import SVR
svr = SVR()

In [87]:
svr.fit(X_train, y_train)

SVR()

In [88]:
y_pred = svr.predict(X_test)

In [89]:
y_pred

array([17.5561784 , 14.36577654, 19.63397234, 28.25543047, 14.02663803,
       15.14661512, 15.65622876, 14.69846537, 17.74841731, 17.10279588,
       17.00871008, 13.11497368, 12.69657312, 15.14661512, 12.61920692,
       14.56276428, 22.36183592, 20.05495874, 15.19753962, 27.62501035,
       20.51137651, 20.70196982, 20.81712863, 13.09052072, 21.43691299,
       14.41684672, 13.85511311, 23.80397724, 19.63397234, 27.64931837,
       22.79293822, 13.8188067 , 20.30086231, 18.25263814, 20.98187239,
       21.0145318 , 13.75259705, 26.55345115, 15.35776158, 14.77444494,
       12.88789193, 13.46643546, 15.6772362 , 15.81001   , 14.37448237,
       12.8355147 , 13.91918958, 17.21837273, 12.89649108, 15.99658633,
       14.83989577, 20.674379  , 26.42594064, 13.792125  , 18.67892859,
       13.73233647, 23.77247816, 13.53584868, 18.67078969, 20.11314707,
       28.25510507])

In [90]:
from sklearn.metrics import r2_score, mean_absolute_error
print(r2_score(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))

0.49798620106004743
4.463296539661224


In [91]:
## Hyperparameter tuning
from sklearn.model_selection import GridSearchCV

# defining paramter range
param_grid = {
  'C' : [0.1, 1, 10, 100, 1000],
  'gamma' : [1, 0.1, 0.01, 0.001, 0.0001],
  'kernel' : ['rbf']
}

In [92]:
grid = GridSearchCV(
  SVR(),
  param_grid=param_grid,
  cv=5,
  refit=True,
  verbose=3
)

In [93]:
grid.fit(
  X_train, y_train
)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.114 total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.008 total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.003 total time=   0.0s
[CV 4/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.015 total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.019 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.096 total time=   0.0s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.078 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.099 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.020 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.102 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [94]:
grid.best_params_

{'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}

In [95]:
grid_prediction = grid.predict(X_test)

In [96]:
from sklearn.metrics import r2_score, mean_absolute_error
print(r2_score(y_test, grid_prediction))
print(mean_absolute_error(y_test, grid_prediction))

0.5630727637616448
4.26048397387227
