In [31]:
!pip install gensim


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [32]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [33]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

In [34]:
king_vec = wv['king']

In [35]:
king_vec.shape

(300,)

In [36]:
import pandas as pd
messages = pd.read_csv('spam.csv')

In [37]:
messages

,label,message
0,ham,"Hey, are we still on for dinner tonight at 7?"
1,spam,Congratulations! You've won a free iPhone. Cli...
2,ham,Can you send me the notes from today's meeting?
3,spam,Get rich quick! Earn $5000/week from home. Sig...
4,ham,Don't forget to bring your ID for the exam tom...
...,...,...
93,spam,You’ve won a smartwatch! Claim it here!
94,ham,Can you print the report before the meeting?
95,spam,Your mobile recharge failed. Retry now!
96,ham,Let’s plan a movie night soon.


In [38]:
import re
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

corpus = []
for i in range(0, len(messages)):
  review = re.sub('[^a-zA-z]', ' ', messages['message'][i]) ## for each sentence take only alphabets
  review = review.lower()
  review = review.split() ## split all words
  
  review = [lemmatizer.lemmatize(word) for word in review] ## don't apply stopwords

  review = ' '.join(review) ## join back
  corpus.append(review)

In [39]:
corpus

['hey are we still on for dinner tonight at',
 'congratulation you ve won a free iphone click here to claim your prize bit ly freephone',
 'can you send me the note from today s meeting',
 'get rich quick earn week from home sign up now',
 'don t forget to bring your id for the exam tomorrow',
 'exclusive deal just for you buy get free limited time offer',
 'i ll be late by minute stuck in traffic',
 'your account ha been suspended verify now fakebank com login',
 'happy birthday hope you have a great day',
 'you ve been selected for a cash reward click to claim',
 'let s catch up this weekend over coffee',
 'win a trip to bali just answer question hurry',
 'can you review my resume before i send it',
 'this is not a drill you ve won a gift card',
 'meeting rescheduled to pm please update your calendar',
 'unlock your full potential with this miracle supplement',
 'thanks for your help yesterday really appreciate it',
 'act now lowest mortgage rate in history apply today',
 'lunch at t

In [40]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

### Get lists of words for every sentence : and it also lowers the case itself

In [43]:
words = []
for sent in corpus:
  sent_token = sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

In [62]:
words

[['hey', 'are', 'we', 'still', 'on', 'for', 'dinner', 'tonight', 'at'],
 ['congratulation',
  'you',
  've',
  'won',
  'free',
  'iphone',
  'click',
  'here',
  'to',
  'claim',
  'your',
  'prize',
  'bit',
  'ly',
  'freephone'],
 ['can', 'you', 'send', 'me', 'the', 'note', 'from', 'today', 'meeting'],
 ['get', 'rich', 'quick', 'earn', 'week', 'from', 'home', 'sign', 'up', 'now'],
 ['don',
  'forget',
  'to',
  'bring',
  'your',
  'id',
  'for',
  'the',
  'exam',
  'tomorrow'],
 ['exclusive',
  'deal',
  'just',
  'for',
  'you',
  'buy',
  'get',
  'free',
  'limited',
  'time',
  'offer'],
 ['ll', 'be', 'late', 'by', 'minute', 'stuck', 'in', 'traffic'],
 ['your',
  'account',
  'ha',
  'been',
  'suspended',
  'verify',
  'now',
  'fakebank',
  'com',
  'login'],
 ['happy', 'birthday', 'hope', 'you', 'have', 'great', 'day'],
 ['you',
  've',
  'been',
  'selected',
  'for',
  'cash',
  'reward',
  'click',
  'to',
  'claim'],
 ['let', 'catch', 'up', 'this', 'weekend', 'over', '

In [63]:
import gensim

## Train Word2vec from scratch
### So we give our own sentences as words for data and vector size we choose as 100. 

In [64]:
model = gensim.models.Word2Vec(
  sentences = words,
  vector_size = 100,
)

In [65]:
## To get all the vocabulary
model.wv.index_to_key

['your',
 'you',
 'the',
 'for',
 'now',
 'to',
 'free',
 'get',
 'll',
 'can',
 've',
 'let',
 'be',
 'won',
 'claim',
 'at',
 'been',
 'with',
 'this',
 'is',
 'today',
 'click',
 'call',
 'me',
 'by',
 'in',
 'on',
 'send',
 'here',
 'meeting',
 'tomorrow',
 'ha',
 'it']

In [66]:
model.corpus_count

98

In [67]:
model.epochs

5

In [71]:
model.wv.similar_by_word('call')

[('at', 0.19689486920833588),
 ('you', 0.18965654075145721),
 ('ha', 0.14267390966415405),
 ('meeting', 0.13719628751277924),
 ('me', 0.10884012281894684),
 ('ve', 0.10066212713718414),
 ('can', 0.07807105779647827),
 ('in', 0.07570403069257736),
 ('click', 0.06837703287601471),
 ('is', 0.050611067563295364)]

In [74]:
model.wv['won']

array([-0.00948984,  0.00960178, -0.00771796, -0.00260387, -0.00492519,
       -0.00501964, -0.00799538, -0.00767034, -0.00455048, -0.0013378 ,
       -0.0050487 ,  0.00604338, -0.00953372, -0.00529463,  0.00939134,
        0.00696925,  0.00772243,  0.00418688,  0.00050883, -0.00611585,
        0.00608156,  0.00266933,  0.00776142,  0.00638163,  0.00792868,
        0.00868711, -0.0099377 , -0.00671829,  0.0013476 ,  0.00644151,
        0.00737688,  0.00543264,  0.00773715, -0.00525508,  0.00655831,
       -0.00410631, -0.0089621 ,  0.00911604,  0.00128835, -0.00278559,
       -0.00246635, -0.00429002,  0.00477358,  0.0044391 , -0.00261366,
       -0.00737016, -0.00363982, -0.00035686,  0.00612335, -0.00278513,
       -0.00012256,  0.00087334, -0.00707794,  0.00209153, -0.00144817,
        0.00277125,  0.00492776, -0.00138116, -0.00282652,  0.00781035,
        0.00502448,  0.00668003,  0.00456697,  0.00869914,  0.00746645,
       -0.00101764,  0.00875566,  0.00470623,  0.0053922 , -0.00

In [75]:
model.wv['won'].shape

(100,)

In [78]:
words[0]

['hey', 'are', 'we', 'still', 'on', 'for', 'dinner', 'tonight', 'at']

In [79]:
words[1]

['congratulation',
 'you',
 've',
 'won',
 'free',
 'iphone',
 'click',
 'here',
 'to',
 'claim',
 'your',
 'prize',
 'bit',
 'ly',
 'freephone']

### Applying Average Word2Vec : For each sentence we will have a 100 dimension vector.
#### Example : I       am       Ayush  => Avg for this sentence
####         [..]    [..]      [..]  =>     [..]  avg of all [0]
####         [..]    [..]      [..]  =>     [..]  avg of all [1]
####         [..]    [..]      [..]  =>     [..]  avg of all [2]
####         [..]    [..]      [..]  =>     [..]x100 avg of all [99]
####         .........100 dimensions each.}

In [86]:
import numpy as np

vocabulary = model.wv.index_to_key

def avg_word2vec(doc):

  # Remove Out-Of-Vocabulary words
  # sent = [word for word in doc if word not in model.wv.index_to_key] # vocabulary = model.wv.index_to_key 
  # print(sent)

  return np.mean([model.wv[word] for word in doc if word in vocabulary], axis=0)


In [87]:
!pip install tqdm


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [88]:
from tqdm import tqdm

In [90]:
## apply for the entire sentence

X = []

for i in tqdm(range(len(words))):
  print("Hello", i)
  X.append(avg_word2vec(words[i]))

100%|██████████| 98/98 [00:00<00:00, 16334.52it/s]

Hello 0
Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
Hello 6
Hello 7
Hello 8
Hello 9
Hello 10
Hello 11
Hello 12
Hello 13
Hello 14
Hello 15
Hello 16
Hello 17
Hello 18
Hello 19
Hello 20
Hello 21
Hello 22
Hello 23
Hello 24
Hello 25
Hello 26
Hello 27
Hello 28
Hello 29
Hello 30
Hello 31
Hello 32
Hello 33
Hello 34
Hello 35
Hello 36
Hello 37
Hello 38
Hello 39
Hello 40
Hello 41
Hello 42
Hello 43
Hello 44
Hello 45
Hello 46
Hello 47
Hello 48
Hello 49
Hello 50
Hello 51
Hello 52
Hello 53
Hello 54
Hello 55
Hello 56
Hello 57
Hello 58
Hello 59
Hello 60
Hello 61
Hello 62
Hello 63
Hello 64
Hello 65
Hello 66
Hello 67
Hello 68
Hello 69
Hello 70
Hello 71
Hello 72
Hello 73
Hello 74
Hello 75
Hello 76
Hello 77
Hello 78
Hello 79
Hello 80
Hello 81
Hello 82
Hello 83
Hello 84
Hello 85
Hello 86
Hello 87
Hello 88
Hello 89
Hello 90
Hello 91
Hello 92
Hello 93
Hello 94
Hello 95
Hello 96
Hello 97


In [91]:
X

[array([-7.4652885e-03,  3.7199424e-03, -1.9977067e-03,  4.3293205e-03,
         1.9414359e-03, -1.1690060e-03,  1.7026229e-03,  3.2344740e-03,
        -2.5884148e-03,  3.3318077e-03,  7.9809535e-05,  1.0928899e-03,
         1.5562713e-03, -3.0383328e-04, -1.8676016e-03, -2.9691097e-03,
         2.6164521e-03, -2.1234672e-03, -1.1184945e-03,  5.1147031e-04,
         2.4300537e-03,  3.4525074e-04,  4.2941365e-03,  5.9961615e-04,
        -8.5087530e-03, -2.3707971e-03, -6.4628352e-06,  5.6908117e-03,
         6.3538342e-04,  3.6008438e-04, -5.3572707e-04, -2.3559376e-03,
        -4.5909677e-04,  5.1252511e-03, -1.4385354e-03,  8.1698811e-03,
         2.7900534e-03, -3.3758294e-03, -6.3220165e-03,  6.5433630e-03,
         6.2239929e-03, -8.2263717e-04, -9.4284117e-04,  1.6533621e-03,
         3.5434689e-03,  2.4278800e-03,  4.8422068e-04, -6.1632185e-03,
         2.1273308e-03, -4.0637585e-03,  6.7388843e-04, -6.4448301e-05,
        -6.9705769e-05,  2.3057312e-04, -4.0367530e-03,  3.48111

In [93]:
len(X)

98

In [94]:
X[0]

array([-7.4652885e-03,  3.7199424e-03, -1.9977067e-03,  4.3293205e-03,
        1.9414359e-03, -1.1690060e-03,  1.7026229e-03,  3.2344740e-03,
       -2.5884148e-03,  3.3318077e-03,  7.9809535e-05,  1.0928899e-03,
        1.5562713e-03, -3.0383328e-04, -1.8676016e-03, -2.9691097e-03,
        2.6164521e-03, -2.1234672e-03, -1.1184945e-03,  5.1147031e-04,
        2.4300537e-03,  3.4525074e-04,  4.2941365e-03,  5.9961615e-04,
       -8.5087530e-03, -2.3707971e-03, -6.4628352e-06,  5.6908117e-03,
        6.3538342e-04,  3.6008438e-04, -5.3572707e-04, -2.3559376e-03,
       -4.5909677e-04,  5.1252511e-03, -1.4385354e-03,  8.1698811e-03,
        2.7900534e-03, -3.3758294e-03, -6.3220165e-03,  6.5433630e-03,
        6.2239929e-03, -8.2263717e-04, -9.4284117e-04,  1.6533621e-03,
        3.5434689e-03,  2.4278800e-03,  4.8422068e-04, -6.1632185e-03,
        2.1273308e-03, -4.0637585e-03,  6.7388843e-04, -6.4448301e-05,
       -6.9705769e-05,  2.3057312e-04, -4.0367530e-03,  3.4811168e-03,
      

In [95]:
X[0].shape

(100,)

In [98]:
X_new = np.array(X) ## Independent features

In [99]:
X_new

array([[-0.00746529,  0.00371994, -0.00199771, ...,  0.00157511,
         0.0034007 ,  0.00126729],
       [ 0.00058732,  0.00277282,  0.00116814, ..., -0.00276438,
        -0.00156782,  0.00366582],
       [-0.00225259, -0.00120724, -0.00119664, ...,  0.00018867,
        -0.00207173,  0.00074893],
       ...,
       [-0.00382941,  0.00076214, -0.00101153, ..., -0.00110884,
         0.00085059,  0.00471733],
       [ 0.00977741,  0.00819166,  0.00129798, ..., -0.00299799,
        -0.00492422, -0.00230784],
       [ 0.00252902, -0.00223438,  0.00236923, ..., -0.00632144,
         0.0017906 , -0.001775  ]], dtype=float32)

In [105]:
X_new.shape

(98, 100)

In [106]:
len(words)

98

### This shows we have got sentence-wise vector embeddings each of dimension = 100.

In [115]:
y = messages[list(map(lambda x: len(x)>0, corpus))] ## Just checking which all sentences have len>0 so we don't take the ones which do not have 

y = pd.get_dummies(messages['label']) ## Dependent/Output features
y = y.astype('int')
## Take the 'ham' row only so we have all containing 0s and 1s for overall data
y = y.iloc[:, 0].values

In [116]:
y.shape

(98,)

### Now as we got sentence-wise vector embeddings of 100 dimension, let's create a Dataframe with each sentence's embeddings of dimension 100 will be divided into 100 columns.

In [132]:
X[0]

array([-7.4652885e-03,  3.7199424e-03, -1.9977067e-03,  4.3293205e-03,
        1.9414359e-03, -1.1690060e-03,  1.7026229e-03,  3.2344740e-03,
       -2.5884148e-03,  3.3318077e-03,  7.9809535e-05,  1.0928899e-03,
        1.5562713e-03, -3.0383328e-04, -1.8676016e-03, -2.9691097e-03,
        2.6164521e-03, -2.1234672e-03, -1.1184945e-03,  5.1147031e-04,
        2.4300537e-03,  3.4525074e-04,  4.2941365e-03,  5.9961615e-04,
       -8.5087530e-03, -2.3707971e-03, -6.4628352e-06,  5.6908117e-03,
        6.3538342e-04,  3.6008438e-04, -5.3572707e-04, -2.3559376e-03,
       -4.5909677e-04,  5.1252511e-03, -1.4385354e-03,  8.1698811e-03,
        2.7900534e-03, -3.3758294e-03, -6.3220165e-03,  6.5433630e-03,
        6.2239929e-03, -8.2263717e-04, -9.4284117e-04,  1.6533621e-03,
        3.5434689e-03,  2.4278800e-03,  4.8422068e-04, -6.1632185e-03,
        2.1273308e-03, -4.0637585e-03,  6.7388843e-04, -6.4448301e-05,
       -6.9705769e-05,  2.3057312e-04, -4.0367530e-03,  3.4811168e-03,
      

In [133]:
X[0].shape

(100,)

In [134]:
X[0].reshape(1,-1).shape

(1, 100)

In [135]:
import pandas as pd
import numpy as np

# Collect all rows in a list
rows = [X[i].reshape(1, -1) for i in range(len(X))]

# Stack them into a single array
data = np.vstack(rows)

# Create the DataFrame
df = pd.DataFrame(data)


In [136]:
df.shape

(98, 100)

### We see 100 columns for each sentence as it has a vector embedding size of 100, so divided into 100 columns for each sentence. After that we can create the train-test split for this new dataframe of 100 columns and rows = len(X) that is the total number of sentences we have in the dataset/corpus. Here we have 98 rows or sentences in the data. 
### So, overall 98 rows as sentences and each sentence has 100 columns which is formed by breaking down embeddings of dimension 100.

In [152]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.007465,0.003720,-0.001998,4.329321e-03,0.001941,-0.001169,0.001703,0.003234,-0.002588,0.003332,...,-0.000769,-0.001268,-0.002773,-0.006513,-0.000787,-0.000749,0.005417,0.001575,0.003401,0.001267
1,0.000587,0.002773,0.001168,-5.969778e-07,-0.003342,-0.001783,0.001310,0.001667,-0.001474,-0.002852,...,0.004595,0.001872,-0.000695,-0.000901,-0.000471,-0.000325,0.000877,-0.002764,-0.001568,0.003666
2,-0.002253,-0.001207,-0.001197,2.039229e-03,0.003493,-0.000027,-0.002259,0.000760,-0.001257,-0.000065,...,-0.001885,0.002633,0.002328,-0.000772,0.003357,0.002270,0.003556,0.000189,-0.002072,0.000749
3,0.000512,-0.001599,0.000907,3.005925e-03,-0.000356,0.003069,0.002741,-0.000911,-0.004837,0.000357,...,0.002600,-0.004355,-0.001479,0.001019,0.000354,-0.004350,0.002216,0.000142,0.002426,-0.000632
4,-0.003438,0.003414,-0.000312,7.990914e-04,-0.002183,-0.001028,0.003424,0.004962,-0.001906,-0.001574,...,-0.000171,0.003271,0.001841,-0.001586,0.009448,0.003765,-0.001188,-0.004812,0.000241,-0.003607


In [153]:
## Independent features
X = df
## Dependent features
y = y

In [154]:
## Train-Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [155]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
74,0.003851,0.001047,0.005354,-0.006345,0.002032,0.002906,-0.003899,0.007401,0.006127,-0.000858,...,-0.001521,-0.002378,0.007295,-0.005789,0.001126,-0.004397,-0.000362,0.007437,0.000551,0.006447
16,-0.000782,0.000227,-0.000779,0.001772,-0.001008,-0.004128,0.001356,0.007565,0.003275,-0.006281,...,-0.003943,-0.000098,0.002339,-0.001505,0.006783,0.002785,0.002228,-0.004102,0.002640,-0.001638
77,-0.000504,0.002514,0.001102,0.000680,-0.004360,-0.001405,0.000004,-0.000856,0.000798,-0.001730,...,0.006215,0.002562,-0.001780,-0.001876,0.000908,-0.002290,-0.003223,-0.001324,-0.001384,0.003118
26,-0.002425,0.000005,-0.000596,0.008050,-0.002540,-0.000540,0.007307,0.003557,-0.003370,0.003184,...,0.003414,-0.001193,0.002397,-0.002122,0.004293,0.000070,-0.004065,-0.001904,-0.000616,0.001238
6,-0.001717,0.002450,0.004542,-0.002453,0.000250,-0.000139,0.002768,0.003955,0.000162,-0.001463,...,-0.001781,-0.003033,0.004442,-0.003194,0.004055,-0.002478,0.002852,0.003758,0.003193,-0.000521


In [156]:
y_train

array([1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1])

In [157]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [158]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [159]:
y_pred = classifier.predict(X_test)

In [160]:
y_pred

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0])

In [161]:
y_test

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0])

In [162]:
from sklearn.metrics import accuracy_score, classification_report
print(accuracy_score(y_test, y_pred))

0.85


In [163]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87        11
           1       0.88      0.78      0.82         9

    accuracy                           0.85        20
   macro avg       0.85      0.84      0.85        20
weighted avg       0.85      0.85      0.85        20

